global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    Team: NETBEARS
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager.aws.netbears.com
rule_files:
- alert-rules.yaml
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
